### ISSUE TITLE
Curious if you've seen this similar project

### ISSUE THREAD

**Issue by bdw429s** [tutuka/node-coldfusion-tester#1]
https://www.npmjs.com/package/testbox-runner

Also, the CommandBox CLI has native ability to run tests with `box testbox run` but it doesn't contain a directory watcher yet.

**Comment by TVScoundrel** [comment]
I have not actually, I will have a look.
Mine does have a directory watcher, that was in fact the whole reason for starting this project ;)

Thanks for the tip Brad!

**Comment by TVScoundrel** [comment]
That package looks nice indeed. But at first glance, and I could be wrong, it looks like it will run all tests all the time.
node-testbox-tester will only run relevant tests upon file-save in order to get real fast feedback...

Please have a look @bdw429s, your feedback would be appreciated.
[Demo video especially for you](https://www.youtube.com/watch?v=WZYHjLWWGM4)

**Comment by bdw429s** [comment]
Wow, thanks for the video @TVScoundrel -- I do like how your using conventions to associate the CFCs with their associated unit test to only run the applicable one.  
We've had it in mind to create watchers in CommandBox as well, so my goal is that people stop having to use Node to do this sort of stuff but write it in CFML instead!  

Great feedback as well on keeping the test results to as few lines as possible. I can see how that's very useful when running the tests inside of a small console window.

Also, you should hop on the CFML Slack team.  It would have been way easier to reach out to you :) 
https://cfml-slack.herokuapp.com/
